### ISSUE TITLE
Still working on this?

### ISSUE THREAD

**Issue by afiaka87** [NotNANtoN/AuViMi#2]
I've been lurking a bit on this project since you started posting on the deep-daze issues. Seems very cool to me and I'm curious how you intend to solve the real-time constraint I think that you have? 

Is that right? You want to try to generate fast enough for a webcam to run _as input_ to deep daze?

**Comment by NotNANtoN** [comment]
Hi! Thanks for you interest :)

Yep, it should run in real time (and it kind of does ready). To have it run smoothly it would be important to have a 3090 on a local server or a 30xx on a laptop - which I unfortunately don't have. 

But I can update the default settings, I recently found a setup that works very nicely by increasing the hidden_size of deep daze. I'm waiting for my PR in deepdaze to be accepted.

I would also like to use StyleCLIP here, as it has the fewest parameters to optimize and converges quite quickly.

**Comment by afiaka87** [comment]
That's fantastic. I need to look into your code more but surely you're not generating higher than 128 px? I wasn't aware a 3090 could generate that quickly actually even on that card!

**Comment by NotNANtoN** [comment]
Im generating at 256 and then upscaling to 512 for deep daze. I think with a 3090 it could be possible to generate at 512, but it might not be worth it in terms of speed.

The StyleCLIP results would be up to 1024x1024. I'm really excited about that. I think with a net trained on faces the mirror might actually work really well.
